name:                register-machine
version:             0.1.0.0
github:              "hnefatl/register-machine"
license:             BSD3
author:              "Keith Collister"
maintainer:          "collisterkeith@gmail.com"
copyright:           "2018 Keith Collister"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/hnefatl/register-machine#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

ghc-options:
- -Wall

executables:
  register-machine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - register-machine

tests:
  register-machine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - register-machine
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - QuickCheck